language: node_js

node_js : 
    - "v4"


addons:
    postgresql: "9.3"

before_script:
  - psql -f test/db.create.postgres.sql -U postgres
  - psql -f test/db.postgres.sql -U postgres



sudo: false